odfe:
  serviceType: ClusterIP
  env:
    team: "teamname"
    cluster.name: "milkyway"
    http.compression: "true"
    odfe_profile: "dev"
    network.host: "0.0.0.0"
    cluster.routing.allocation.disk.threshold_enabled: "false"
  image:
    repository: amazon/opendistro-for-elasticsearch
    tag: 1.2.0
    pullPolicy: Always
  stateful:
    enabled: true
    class: "rook-ceph-block"
  security:
    enabled: true
    generate_secrets: true
    volumeMounts:
      - name: certs
        mountPath: "/usr/share/elasticsearch/config/node.pem"
        subPath: node.pem
      - name: certs
        mountPath: "/usr/share/elasticsearch/config/node-key.pem"
        subPath: node-key.pem
      - name: certs
        mountPath: "/usr/share/elasticsearch/config/root-ca.pem"
        subPath: root-ca.pem
      - name: certs
        mountPath: "/usr/share/elasticsearch/config/admin.pem"
        subPath: admin.pem
      - name: certs
        mountPath: "/usr/share/elasticsearch/config/admin-key.pem"
        subPath: admin-key.pem
master:
  replicas: 3
  antiAffinity: "soft"
  resources:
    requests:
      memory: 256Mi
  env:
    ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    node.master: true
    node.data: false
    node.ingest: false
  stateful:
    size: 1Gi

ingest:
  replicas: 2
  antiAffinity: "soft"
  heapMemory: 256m
  resources:
    requests:
      memory: 256Mi
  env:
    ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    node.master: false
    node.data: false
    node.ingest: true

data:
  replicas: 3
  antiAffinity: "soft"
  heapMemory: 256m
  resources:
    requests:
      memory: 256Mi
  env:
    ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    node.master: false
    node.data: true
    node.ingest: false
  stateful:
    size: 4Gi

kibana:
  enabled: true
  replicas: 1
  httpPort: 80
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 100m
  security:
    env:
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY: /usr/share/kibana/config/node.key
      SERVER_SSL_CERTIFICATE: /usr/share/kibana/config/node.pem