{{ if .Values.odfe.istio.inject }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    app: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.TEAM }}
spec:
  gateways:
  - istio-system/ingress-gateway-dev-nav-no
  hosts:
  - {{ template "fullname" . }}-kibana.dev-nav.no
  http:
  - route:
    - destination:
        host: {{ template "fullname" . }}-kibana
        port:
          number: 5601
        subset: ""
      weight: 100
{{ end }}
