{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.team  }}
    role: kibana
spec:
  type: {{ .Values.odfe.serviceType }}
  selector:
    component: {{ template "fullname" . }}
    role: kibana
    team: {{ .Values.odfe.env.team  }}
  ports:
  - name: https
    port: 443
    targetPort: 5601
    protocol: TCP
{{- end }}
