{{ if .Values.odfe.generate_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.team  }}  
type: Opaque
stringData:
  elasticsearch.yml: |-
    opendistro_security.disabled: "false"
    opendistro_security.allow_unsafe_democertificates: "false"
    opendistro_security.allow_default_init_securityindex: "true"
    opendistro_security.audit.type: internal_elasticsearch
    opendistro_security.enable_snapshot_restore_privilege: "true"
    opendistro_security.check_snapshot_restore_write_privileges: "true"
    opendistro_security.audit.config.disabled_rest_categories: NONE
    opendistro_security.audit.config.disabled_transport_categories: NONE
    opendistro_security.ssl.transport.pemcert_filepath: node.pem
    opendistro_security.ssl.transport.pemkey_filepath: node-key.pem
    opendistro_security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
    opendistro_security.ssl.transport.enforce_hostname_verification: "false"
    opendistro_security.ssl.http.enabled: "true"
    opendistro_security.ssl.http.pemcert_filepath: node.pem
    opendistro_security.ssl.http.pemkey_filepath: node-key.pem
    opendistro_security.ssl.http.pemtrustedcas_filepath: root-ca.pem
    opendistro_security.authcz.admin_dn: 
      - "CN=ADMIN,OU=NAV,O=NAV,L=OSLO,ST=OSLO,C=NO"
    opendistro_security.nodes_dn: 
      - "CN=NODE,OU=NAV,O=NAV,L=OSLO,ST=OSLO,C=NO"
    opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
  internal_users.yml: |-
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: {{ .Values.odfe.security.password.hash }} 
      reserved: true
      backend_roles:
      - "admin"
      description: "admin user"
    kibanaserver:
      hash: {{ .Values.odfe.security.password.hash }}
      reserved: true
      description: "kibanaserver user"
    kibanaro:
      hash: {{ .Values.odfe.security.password.hash }}
      reserved: false
      backend_roles:
      - "kibanauser"
      - "readall"
      attributes:
        attribute1: "value1"
        attribute2: "value2"
        attribute3: "value3"
      description: "kibanaro user"
    logstash:
      hash: {{ .Values.odfe.security.password.hash }}
      reserved: false
      backend_roles:
      - "logstash"
      description: "logstash user"
    readall:
      hash: {{ .Values.odfe.security.password.hash }}
      reserved: false
      backend_roles:
      - "readall"
      description: "readall user"
    snapshotrestore:
      hash: {{ .Values.odfe.security.password.hash }}
      reserved: false
      backend_roles:
      - "snapshotrestore"
      description: "snapshotrestore user"
{{ end }}
