{{- if .Values.odfe.generate_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-exporter-secrets
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
type: Opaque
stringData: 
{{- if .Values.odfe.ssl.http.enabled }}
  ES_URI: https://monitor:{{ .Values.exporter.password }}@{{ template "fullname" . }}:9200
{{- else }}
  ES_URI: http://monitor:{{ .Values.exporter.password }}@{{ template "fullname" . }}:9200  
{{- end }}
