apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-prometheus-exporter
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.team  }}
    role: prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      role: prometheus-exporter
      component: {{ template "fullname" . }}
      team: {{ .Values.odfe.env.team  }}
  template:
    metadata:
      labels:
        role: prometheus-exporter
        component: {{ template "fullname" . }}
        team: {{ .Values.odfe.env.team  }}
    spec:
      containers:
      - command:
        - /bin/elasticsearch_exporter
        - --es.all
        - --es.cluster_settings
        - --es.indices
        - --es.indices_settings
        - --es.shards
        - --es.snapshots
{{- if .Values.odfe.security.enabled }}
        - --es.client-private-key=/usr/share/certs/client-key.pem
        - --es.client-cert=/usr/share/certs/client.pem
        - --es.ca=/usr/share/certs/root-ca.pem
        - --es.uri=https://{{ template "fullname" . }}:9200
        - --es.ssl-skip-verify
{{- else }}
        - --es.uri=http://{{ template "fullname" . }}:9200
{{- end }} 
        image: justwatch/elasticsearch_exporter:1.1.0
        livenessProbe:
          httpGet:
            path: /health
            port: 9114
          initialDelaySeconds: 45
          timeoutSeconds: 10
        name: prometheus-exporter
        ports:
        - containerPort: 9114
{{- if .Values.odfe.security.enabled }}
        volumeMounts:
        - mountPath: /usr/share/certs/client.pem
          name: certs
          subPath: client.pem
        - mountPath: /usr/share/certs/client-key.pem
          name: certs
          subPath: client-key.pem
        - mountPath: /usr/share/certs/root-ca.pem
          name: certs
          subPath: root-ca.pem
      volumes:
      - name: certs
        secret:
          secretName: {{ template "fullname" . }}-certs
{{- end }}
        readinessProbe:
          httpGet:
            path: /health
            port: 9114
          initialDelaySeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi