{{- if .Values.odfe.generate_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-kibana-secrets
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
type: Opaque
stringData:
  kibana.yml: |- 
    server.name: kibana
    server.host: "0"
    elasticsearch.ssl.verificationMode: none
    elasticsearch.username: kibanaserver
    elasticsearch.password: {{ .Values.kibana.password }}  
    elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
    opendistro_security.multitenancy.enabled: true
    opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
    opendistro_security.readonly_mode.roles: ["kibana_read_only"]
{{- end }}
