{{ if and .Values.odfe.security.enabled .Values.odfe.security.generate_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-certs
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.team  }}  
type: Opaque
stringData:
  node.pem: |- 
{{ .Files.Get ".certs/node.pem" | indent 4 }} 
  node-key.pem: |-
{{ .Files.Get ".certs/node-key.pem" | indent 4 }}     
  root-ca.pem: |-
{{ .Files.Get ".certs/root-ca.pem" | indent 4 }}     
  admin.pem: |-
{{ .Files.Get ".certs/admin.pem" | indent 4 }}     
  admin-key.pem: |-
{{ .Files.Get ".certs/admin-key.pem" | indent 4 }}     
{{ end }}  
