{{ if .Values.odfe.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.TEAM }}
spec:
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
      to:
        - operation:
            methods:
              - '*'
            paths:
              - '*'
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/pam-internal-search-api
      to:
        - operation:
            methods:
              - '*'
            paths:
              - '*'
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/pam-index
      to:
        - operation:
            methods:
              - '*'
            paths:
              - '*'
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/pam-er-sync
      to:
        - operation:
            methods:
              - '*'
            paths:
              - '*'
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/pam-search-api
      to:
        - operation:
            methods:
              - '*'
            paths:
              - '*'
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/pam-internalad-indexer
      to:
        - operation:
            methods:
              - '*'
            paths:
              - '*'
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/{{ template "fullname" . }}
      to:
        - operation:
            methods:
              - '*'
            paths:
              - '*'
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
{{ end }}
