apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-prometheus-exporter
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.TEAM }}
    role: prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      role: prometheus-exporter
      component: {{ template "fullname" . }}
      team: {{ .Values.odfe.env.TEAM }}
  template:
    metadata:
      labels:
        role: prometheus-exporter
        component: {{ template "fullname" . }}
        team: {{ .Values.odfe.env.TEAM }}
    spec:
      containers:
      - command:
        - /bin/elasticsearch_exporter
        - --es.all
        - --es.cluster_settings
        - --es.indices
        - --es.indices_settings
        - --es.shards
        - --es.snapshots
        - --es.ca=/usr/share/elasticsearch/config/root-ca.pem
        - --es.client-private-key=/usr/share/elasticsearch/config/monitor-key.pem
        - --es.client-cert=/usr/share/elasticsearch/config/monitor.pem
        - --es.ssl-skip-verify
        image: justwatch/elasticsearch_exporter:1.1.0
        name: prometheus-exporter
        env:
          - name: ES_URI
            value: https://{{ template "fullname" . }}:9200
        ports:
        - containerPort: 9114
        livenessProbe:
          httpGet:
            path: /health
            port: 9114
          initialDelaySeconds: 45
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9114
          initialDelaySeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi
{{ if .Values.odfe.security.enabled }}
        volumeMounts:
{{ toYaml .Values.odfe.security.volumeMounts | indent 10 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ template "fullname" . }}-certs
        - name: config
          secret:
            secretName: {{ template "fullname" . }}-config
{{- end }}
