apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-prometheus-exporter
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.TEAM }}
    role: prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      role: prometheus-exporter
      component: {{ template "fullname" . }}
      team: {{ .Values.odfe.env.TEAM }}
  template:
    metadata:
      labels:
        role: prometheus-exporter
        component: {{ template "fullname" . }}
        team: {{ .Values.odfe.env.TEAM }}
    spec:
      containers:
        env:
          - name: ES_URI
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-exporter-secrets
                key: ES_URI
      - command:
        - /bin/elasticsearch_exporter
        - --es.all
        - --es.cluster_settings
        - --es.indices
        - --es.indices_settings
        - --es.shards
        - --es.snapshots
        image: justwatch/elasticsearch_exporter:1.1.0
        livenessProbe:
          httpGet:
            path: /health
            port: 9114
          initialDelaySeconds: 45
          timeoutSeconds: 10
        name: prometheus-exporter
        ports:
        - containerPort: 9114
        readinessProbe:
          httpGet:
            path: /health
            port: 9114
          initialDelaySeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi