{{- if .Values.kibana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.team  }}
    role: kibana
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
      component: {{ template "fullname" . }}
      role: kibana
      team: {{ .Values.odfe.env.team  }}
  template:
    metadata:
      labels:
        component: {{ template "fullname" . }}
        role: kibana
        team: {{ .Values.odfe.env.team  }}
    spec:
      containers:
      - name: {{ template "fullname" . }}-kibana
        image: {{ .Values.odfe.image.repository }}-kibana:{{ .Values.odfe.image.tag }}
        imagePullPolicy: {{ .Values.odfe.image.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- range $key, $value :=  .Values.odfe.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value :=  .Values.kibana.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: ELASTICSEARCH_URL
          value: http://{{ template "fullname" . }}:9200
        - name: ELASTICSEARCH_HOSTS
          value: http://{{ template "fullname" . }}:9200
        {{- range $key, $value :=  .Values.kibana.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
{{ toYaml .Values.kibana.resources | indent 12 }}
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
{{- end }}
